Updating svelte frontend formatting

diff --git a/e2e-tests/scripts/nns-canister-build b/e2e-tests/scripts/nns-canister-build
--- a/e2e-tests/scripts/nns-canister-build
+++ b/e2e-tests/scripts/nns-canister-build
@@ -6,7 +6,7 @@ DOWNLOAD_DIR="$(realpath ../../target/ic)"
 IC_COMMIT=eba88796cf8dff32f5788c9167cdd8e292b6072a
 
 help_text() {
-    cat <<-EOF
+  cat <<-EOF
 	Builds some NNS canisters locally:
 	- ledger
 
@@ -21,29 +21,35 @@ help_text() {
 	EOF
 }
 
-while (($# > 0)) ; do
-        arg="$1" ; shift 1
-        case "$arg" in
-        --help)
-                help_text
-                exit 0 ;;
-        --download-dir)
-                DOWNLOAD_DIR="$(realpath "$1")"
-                test -d "$DOWNLOAD_DIR" || {
-                        printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
-                        exit 1
-                } >&2
-                shift 1 ;;
-	--ic-commit)
-		IC_COMMIT="$1" ; shift 1 ;;
-        *)
-                {
-                        printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
-                        printf "Usage:"
-                        help_text
-                } >&2
-                exit 1 ;;
-        esac
+while (($# > 0)); do
+  arg="$1"
+  shift 1
+  case "$arg" in
+  --help)
+    help_text
+    exit 0
+    ;;
+  --download-dir)
+    DOWNLOAD_DIR="$(realpath "$1")"
+    test -d "$DOWNLOAD_DIR" || {
+      printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
+      exit 1
+    } >&2
+    shift 1
+    ;;
+  --ic-commit)
+    IC_COMMIT="$1"
+    shift 1
+    ;;
+  *)
+    {
+      printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
+      printf "Usage:"
+      help_text
+    } >&2
+    exit 1
+    ;;
+  esac
 done
 
 mkdir -p "${DOWNLOAD_DIR}"
diff --git a/e2e-tests/scripts/nns-canister-download b/e2e-tests/scripts/nns-canister-download
--- a/e2e-tests/scripts/nns-canister-download
+++ b/e2e-tests/scripts/nns-canister-download
@@ -7,7 +7,7 @@ DOWNLOAD_DIR="$PWD/target/ic"
 NO_CLOBBER=""
 
 help_text() {
-    cat <<-EOF
+  cat <<-EOF
 	Downloads prebuilt internet computer artifacts:
 	- NNS wasm canisters
 	- NNS wasm canister installer
@@ -31,59 +31,63 @@ help_text() {
 	EOF
 }
 
-
-while (($# > 0)) ; do
-	arg="$1" ; shift 1
-	case "$arg" in
-	--help)
-		help_text
-		exit 0 ;;
-	--download-dir)
-                DOWNLOAD_DIR="$(realpath "$1")"
-                test -d "$DOWNLOAD_DIR" || {
-                        printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
-                        exit 1
-                } >&2
-                shift 1 ;;
-	--ic-commit)
-		IC_COMMIT="$1" ; shift 1 ;;
-	--no-clobber)
-		NO_CLOBBER=nc ;;
-	*)
-		{
-			printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg" 
-			printf "Usage:"
-			help_text
-		} >&2
-		exit 1 ;;
-	esac
+while (($# > 0)); do
+  arg="$1"
+  shift 1
+  case "$arg" in
+  --help)
+    help_text
+    exit 0
+    ;;
+  --download-dir)
+    DOWNLOAD_DIR="$(realpath "$1")"
+    test -d "$DOWNLOAD_DIR" || {
+      printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
+      exit 1
+    } >&2
+    shift 1
+    ;;
+  --ic-commit)
+    IC_COMMIT="$1"
+    shift 1
+    ;;
+  --no-clobber)
+    NO_CLOBBER=nc
+    ;;
+  *)
+    {
+      printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
+      printf "Usage:"
+      help_text
+    } >&2
+    exit 1
+    ;;
+  esac
 done
-
 
 mkdir -p "$DOWNLOAD_DIR"
 echo "$DOWNLOAD_DIR"
 
 get_binary() {
-	local FILENAME="$1"
-	if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"
-	then return
-	fi
-	local TMP_FILE="$(mktemp)"
-	curl "https://download.dfinity.systems/ic/${IC_COMMIT}/release/${FILENAME}.gz" | gunzip > "$TMP_FILE"
-	install -m 755 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
-	rm "$TMP_FILE"
+  local FILENAME="$1"
+  if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"; then
+    return
+  fi
+  local TMP_FILE="$(mktemp)"
+  curl "https://download.dfinity.systems/ic/${IC_COMMIT}/release/${FILENAME}.gz" | gunzip >"$TMP_FILE"
+  install -m 755 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
+  rm "$TMP_FILE"
 }
 get_wasm() {
-	local FILENAME="$1"
-	if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"
-	then return
-	fi
-	local TMP_FILE="$(mktemp)"
-	curl "https://download.dfinity.systems/ic/${IC_COMMIT}/canisters/${FILENAME}.gz" | gunzip > "$TMP_FILE"
-	install -m 644 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
-	rm "$TMP_FILE"
+  local FILENAME="$1"
+  if test -e "$DOWNLOAD_DIR/$FILENAME" && test -n "${NO_CLOBBER:-}"; then
+    return
+  fi
+  local TMP_FILE="$(mktemp)"
+  curl "https://download.dfinity.systems/ic/${IC_COMMIT}/canisters/${FILENAME}.gz" | gunzip >"$TMP_FILE"
+  install -m 644 "$TMP_FILE" "$DOWNLOAD_DIR/$FILENAME"
+  rm "$TMP_FILE"
 }
-
 
 get_binary ic-nns-init
 get_wasm registry-canister.wasm
diff --git a/e2e-tests/scripts/nns-canister-install b/e2e-tests/scripts/nns-canister-install
--- a/e2e-tests/scripts/nns-canister-install
+++ b/e2e-tests/scripts/nns-canister-install
@@ -5,7 +5,7 @@ cd "$(dirname "$0")/../.."
 DOWNLOAD_DIR="target/ic"
 
 help_text() {
-    cat <<-EOF
+  cat <<-EOF
 	Installs NNS canisters locally.
 
 	Note: This should be done immediately after a "dfx start --clean"
@@ -19,28 +19,31 @@ help_text() {
 	EOF
 }
 
-
-while (($# > 0)) ; do
-	arg="$1" ; shift 1
-	case "$arg" in
-	--help)
-		help_text
-		exit 0 ;;
-	--download-dir)
-		DOWNLOAD_DIR="$(realpath "$1")"
-		test -d "$DOWNLOAD_DIR" || {
-			printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
-			exit 1
-		} >&2
-		shift 1 ;;
-	*)
-		{
-			printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg" 
-			printf "Usage:"
-			help_text
-		} >&2
-		exit 1 ;;
-	esac
+while (($# > 0)); do
+  arg="$1"
+  shift 1
+  case "$arg" in
+  --help)
+    help_text
+    exit 0
+    ;;
+  --download-dir)
+    DOWNLOAD_DIR="$(realpath "$1")"
+    test -d "$DOWNLOAD_DIR" || {
+      printf "ERROR: %s '%s'\n" "Download dir does not exist:" "$1"
+      exit 1
+    } >&2
+    shift 1
+    ;;
+  *)
+    {
+      printf "ERROR: %s '%s'\n" "Unknown argument:" "$arg"
+      printf "Usage:"
+      help_text
+    } >&2
+    exit 1
+    ;;
+  esac
 done
 
 test -x "${DOWNLOAD_DIR}/ic-nns-init" || {
