fmt

diff --git a/scripts/nns-dapp/e2e-test-metrics-present b/scripts/nns-dapp/e2e-test-metrics-present
--- a/scripts/nns-dapp/e2e-test-metrics-present
+++ b/scripts/nns-dapp/e2e-test-metrics-present
@@ -22,12 +22,12 @@ METRICS_URL="$(dfx-canister-url --raw --network "$DFX_NETWORK" nns-dapp)/metrics
 REFERENCE_KEYS_FILE="$0.keys"
 NETWORK_KEYS_FILE=",nns-dapp-metrics-$DFX_NETWORK.keys"
 NETWORK_METRICS_FILE=",nns-dapp-metrics-$DFX_NETWORK.txt"
-curl "$METRICS_URL" > "$NETWORK_METRICS_FILE"
-sed -nE '/^([a-z_]+).*/{s//\1/g;p}' "$NETWORK_METRICS_FILE" | sort > "$NETWORK_KEYS_FILE"
+curl "$METRICS_URL" >"$NETWORK_METRICS_FILE"
+sed -nE '/^([a-z_]+).*/{s//\1/g;p}' "$NETWORK_METRICS_FILE" | sort >"$NETWORK_KEYS_FILE"
 diff "$REFERENCE_KEYS_FILE" "$NETWORK_KEYS_FILE" || {
-    echo "ERROR: The list of metrics in  does not match the reference set."
-    echo "Expected metrics are in: $REFERENCE_KEYS_FILE"
-    echo "Actual metrics are in:  $NETWORK_KEYS_FILE"
-    exit 1
+  echo "ERROR: The list of metrics in  does not match the reference set."
+  echo "Expected metrics are in: $REFERENCE_KEYS_FILE"
+  echo "Actual metrics are in:  $NETWORK_KEYS_FILE"
+  exit 1
 } >&2
 # rm "$NETWORK_KEYS_FILE" "$NETWORK_METRICS_FILE"
