Tighter nns URL logic

diff --git a/scripts/nns-dapp/release b/scripts/nns-dapp/release
--- a/scripts/nns-dapp/release
+++ b/scripts/nns-dapp/release
@@ -15,7 +15,9 @@ print_help() {
 source "$SOURCE_DIR/clap.bash"
 # Define options
 clap.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="local"
+clap.define long=nns_url desc="The dfx network to use" variable=DFX_NNS_URL
 clap.define short=N long=neuron desc="The neuron ID to propose with" variable=DFX_NEURON_ID
+clap.define short=k long=hsm_key_id desc="The HSM key ID" variable=DFX_HSM_KEY_ID default=""
 clap.define short=i long=identity desc="The dfx identity to use" variable=DFX_IDENTITY default="$(dfx identity whoami)"
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
@@ -38,7 +40,27 @@ cd "$(dirname "$0")/../../.."
   exit 1
 } >&2
 
-read -rp "HSM Pin: " DFX_HSM_PIN
+# Gets the HSM key, if applicable
+[[ "${DFX_HSM_KEY_ID:-}" != "" ]] || {
+  DFX_HSM_KEY_ID="$(jq -re '.hsm.key_id // empty' "${HOME}/.config/dfx/identity/${DFX_IDENTITY}/identity.json")"
+}
+# Gets the authentication mechanism
+PEM_PATH="$HOME/.config/dfx/identity/${DFX_IDENTITY}/identity.pem"
+if [[ "${DFX_HSM_KEY_ID:-}" != "" ]]; then
+  read -rp "HSM Pin: " DFX_HSM_PIN
+  AUTH_ARGS=(--pin "$DFX_HSM_PIN" --use-hsm --key-id "${DFX_HSM_KEY_ID}" --slot 0)
+elif test -e "$PEM_PATH"; then
+  [[ "$(jq .encryption "$HOME/.config/dfx/identity/${DFX_IDENTITY}/identity.json")" == "null" ]] || {
+    echo "ERROR: ic-admin does not support encrypted pem files."
+    exit 1
+  } >&2
+  AUTH_ARGS=(--secret-key-pem "$PEM_PATH")
+else
+  {
+    echo "ERROR: Please specify the HSM key ID (usually 01) or use a dfx identity with an unencrypted pem file."
+    exit 1
+  } >&2
+fi
 
 # Gets the nns-dapp  canister ID
 NNS_DAPP_CANISTER_ID="$(dfx canister id nns-dapp --network "$DFX_NETWORK")"
@@ -51,16 +73,20 @@ if [[ "${DFX_NETWORK:-}" =~ mainnet|ic ]]; then
   } >&2
 fi
 
-# Gets the proposal URL
-DFX_NNS_URL="$(dfx-network-provider --network "$DFX_NETWORK")"
-# ... just checking...
-if [[ "${DFX_NETWORK:-}" =~ mainnet|ic ]]; then
-  [[ "$DFX_NNS_URL" == "https://ic0.app" ]] || {
-    echo "ERROR: Is the proposal URL really correct? '$DFX_NNS_URL'"
-    echo "       If so, please update this script: '${BASH_SOURCE[0]}'"
-    exit 1
-  } >&2
-fi
+# Gets the NNS URL
+[[ "${DFX_NNS_URL:-}" != "" ]] || {
+  if [[ "${DFX_NETWORK:-}" =~ mainnet|ic ]]; then
+    DFX_NNS_URL="https://ic0.app"
+  else
+    # Try to use the snsdemo script for getting the provider for testnets and local replicas.
+    DFX_NNS_URL="$(dfx-network-provider --network "$DFX_NETWORK")"
+  fi
+}
+[[ "${DFX_NNS_URL:-}" != "" ]] || {
+  echo "ERROR: Unable to determine the nns URL."
+  echo "       Please specify --nns_url as a command line argument."
+  exit 1
+} >&2
 
 # Gets the wasm
 # Note: If the wasm is not provided, the SHA will fail.
@@ -81,7 +107,7 @@ test -e "$ARG_PATH" || {
 } >&2
 
 # Prepares the command
-set ic-admin --pin "$DFX_HSM_PIN" --nns-url "$DFX_NNS_URL" --use-hsm --key-id 01 --slot 0 propose-to-change-nns-canister --proposer "$DFX_NEURON_ID" --canister-id "$AGGREGATOR_CANISTER_ID" --mode upgrade --wasm-module-path "$WASM" --summary-file ./release/AGGREGATOR_PROPOSAL.md --wasm-module-sha256 "$SHA" --arg "$ARG_PATH"
+set ic-admin "${AUTH_ARGS[@]}" --nns-url "$DFX_NNS_URL" propose-to-change-nns-canister --proposer "$DFX_NEURON_ID" --canister-id "$AGGREGATOR_CANISTER_ID" --mode upgrade --wasm-module-path "$WASM" --summary-file ./release/AGGREGATOR_PROPOSAL.md --wasm-module-sha256 "$SHA" --arg "$ARG_PATH"
 # ... just checking...
 echo
 echo PLEASE REVIEW THIS COMMAND:
