more tests

diff --git a/scripts/nns-dapp/release-sop b/scripts/nns-dapp/release-sop
--- a/scripts/nns-dapp/release-sop
+++ b/scripts/nns-dapp/release-sop
@@ -41,15 +41,24 @@ if [ "$IS_NEW_RELEASE" = "false" ] && [ "$CONTINUE" = "false" ]; then
   exit 1
 fi
 
+NOT_MOCKED_COMMANDS=(
+  echo
+  get_build_hash
+  review_proposal
+  review_feature_flags
+)
+
 execute() {
   if ! [ "${MOCK_JSON:-}" ]; then
     "$@"
     return
   fi
-  if [[ "$1" == "echo" || "$1" == "get_build_hash" ]]; then
-    "$@"
-    return
-  fi
+  for not_mocked in "${NOT_MOCKED_COMMANDS[@]}"; do
+    if [ "$1" = "$not_mocked" ]; then
+      "$@"
+      return
+    fi
+  done
   cmd=$(printf "%q " "$@" | sed 's/ $//')
   entry="$(jq --arg command "$cmd" '.behavior[] | select(.command == $command)' "$MOCK_JSON")"
   if ! [ "$entry" ]; then
@@ -203,18 +212,18 @@ confirm_cmd() {
 confirm_manual() {
   local label message input
   label="$1"
-  message="$2"
+  shift
   value="$(checklist_get "$label")"
   if [ "$value" ]; then
     echo "$label: Was already done. Skipping."
     return
   fi
-  (
-    echo
-    echo -e "$message"
-    echo
-    echo "When you've done that ☝️  confirm by entering 'y':"
-  ) >&2
+  if ! execute "$@"; then
+    echo "$label: Failed"
+    exit 1
+  fi
+  echo
+  echo "When you've done that ☝️  confirm by entering 'y':"
   if ! [ "${MOCK_JSON:-}" ]; then
     read -r input
     if [[ ${input:-} != "y" ]]; then
@@ -384,7 +393,7 @@ get_build_hash() {
 review_proposal() {
   echo "==  release/PROPOSAL.md:  ============================================"
   echo
-  cat "$TOP_DIR/release/PROPOSAL.md"
+  execute cat "release/PROPOSAL.md"
   echo
   echo "======================================================================"
   echo
@@ -392,9 +401,7 @@ review_proposal() {
 }
 
 review_feature_flags() {
-  if ! [ "${MOCK_JSON:-}" ]; then
-    idl2json <"$TOP_DIR/release/nns-dapp-arg-mainnet.did" | jq '.[] | .args[] | select(."0" == "FEATURE_FLAGS") | ."1" | fromjson'
-  fi
+  execute cat "release/nns-dapp-arg-mainnet.did" | idl2json | jq '.[] | .args[] | select(."0" == "FEATURE_FLAGS") | ."1" | fromjson'
   echo
   echo "Review the feature flags above ☝️  ."
 }
@@ -412,7 +419,7 @@ post_proposal_on_slack() {
     echo "* $NNS_DAPP_PROPOSAL_URL"
     echo
     echo '````'
-    cat "$TOP_DIR/release/PROPOSAL.md"
+    cat "release/PROPOSAL.md"
     echo '````'
     echo
     echo "Post the above ☝️  on $NNS_RELEASES_CHANNEL_URL."
@@ -454,11 +461,11 @@ record "NNS-dapp staging canister ID" dfx canister id nns-dapp --network staging
 verify "NNS-dapp staging canister ID" "Current NNS-dapp staging canister ID" dfx canister id nns-dapp --network staging
 CANISTER_ID="$(checklist_must_get "NNS-dapp staging canister ID")"
 confirm_cmd DFX_NETWORK=staging ./config.sh
-confirm_cmd dfx canister install nns-dapp --argument "$(execute cat nns-dapp-arg-staging.did)" --network staging --wasm "$TOP_DIR/release/ci/nns-dapp.wasm.gz"
+confirm_cmd dfx canister install nns-dapp --argument "$(execute cat nns-dapp-arg-staging.did)" --network staging --wasm ./release/ci/nns-dapp.wasm.gz
 record "Staging URL" echo "https://$CANISTER_ID.nnsdapp.dfinity.network/"
 verify "CI NNS-dapp WASM hash" "Staging WASM hash" get_module_hash_from_network staging
 record "Post RC on Slack" post_rc_on_slack
-confirm_manual "Update playground" "Update the 'Playground' bookmark on the #eng-nns-dapp Slack channel to point to the new release candidate.\n\nSlack channel: https://dfinity.slack.com/channels/eng-nns-dapp\nNew Playground bookmark: $(checklist_must_get "Staging URL")"
+confirm_manual "Update playground" echo "Update the 'Playground' bookmark on the #eng-nns-dapp Slack channel to point to the new release candidate.\n\nSlack channel: https://dfinity.slack.com/channels/eng-nns-dapp\nNew Playground bookmark: $(checklist_must_get "Staging URL")"
 
 # Release
 record "Canister IDs" "$SOURCE_DIR/../canister_ids" --export --network staging
@@ -466,11 +473,11 @@ record "Build hashes" verify_build
 confirm_cmd "$SOURCE_DIR/release-template"
 confirm_cmd "$SOURCE_DIR/release-check"
 verify "CI NNS-dapp WASM hash" "Built NNS-dapp WASM hash" get_build_hash nns-dapp.wasm.gz
-confirm_manual "Review proposal" "$(review_proposal)"
-confirm_manual "Review feature flags" "$(review_feature_flags)"
+confirm_manual "Review proposal" review_proposal
+confirm_manual "Review feature flags" review_feature_flags
 record "CI mainnet args hash" "$SOURCE_DIR/get-hash-from-ci-log" --commit tags/release-candidate --filename nns-dapp-arg-mainnet.bin
 verify "CI mainnet args hash" "Built mainnet args hash" get_build_hash nns-dapp-arg-mainnet.bin
-PROPOSAL_ID_FILE="$TOP_DIR/release/proposal_id"
+PROPOSAL_ID_FILE="release/proposal_id"
 confirm_cmd "$SOURCE_DIR/release" --save-proposal-id-to-file "$PROPOSAL_ID_FILE"
 record "Proposal ID" cat "$PROPOSAL_ID_FILE"
 PROPOSAL_ID="$(checklist_must_get "Proposal ID")"
@@ -481,6 +488,6 @@ confirm_cmd git tag "$PROPOSAL_TAG"
 confirm_cmd git push origin "tags/$PROPOSAL_TAG"
 confirm_cmd git checkout "$BRANCH_NAME"
 record "Post proposal on Slack" post_proposal_on_slack
-confirm_manual "Schedule voting" "Schedule an appointment for trusted neurons voting (in 3 days)"
-confirm_manual "Schedule silence alerts" "Create an event to remind yourself to silence alerts before voting"
-confirm_manual "Forum post" "Create a forum post if there's something worth sharing"
+confirm_manual "Schedule voting" echo "Schedule an appointment for trusted neurons voting (in 3 days)"
+confirm_manual "Schedule silence alerts" echo "Create an event to remind yourself to silence alerts before voting"
+confirm_manual "Forum post" echo "Create a forum post if there's something worth sharing"
