formatting

diff --git a/scripts/nns-dapp/run-ci-job b/scripts/nns-dapp/run-ci-job
--- a/scripts/nns-dapp/run-ci-job
+++ b/scripts/nns-dapp/run-ci-job
@@ -1,10 +1,13 @@
 #!/bin/bash
+set -euo pipefail
+
+SOURCE_DIR="$(dirname "${BASH_SOURCE[0]}")"
 
 print_help() {
 cat <<-EOF
 
 	Runs a github CI job on the current branch.
-	Needs `gh` to be installed and logged in (https://cli.github.com/manual).
+	Needs [gh](https://cli.github.com/manual) to be installed and logged in.
 
 	How to find view id:
     1. Go to the github actions page for the current branch
@@ -21,18 +24,19 @@ cat <<-EOF
 	EOF
 }
 
-ROOT_DIR=$(git rev-parse --show-toplevel)
 # Source the clap.bash file ---------------------------------------------------
-source "$ROOT_DIR/scripts/clap.bash"
+# shellcheck disable=SC1091
+source "$SOURCE_DIR/../clap.bash"
 ## Define options
 clap.define long=view desc="Github view id to rerun" variable=VIEW_ID
 clap.define long=job-name desc="Github job id to rerun" variable=JOB_NAME
 clap.define long=times desc="How many times to run" variable=TIMES_TO_RUN
 ## Source the output file ------------------------------------------------------
+# shellcheck disable=SC1090
 source "$(clap.build)"
 
 if [ "$VIEW_ID" == "" ]; then
-  echo "Please provide the view id '--view 00000000' " >&2
+  echo "Please provide the view id '--view 00000000'" >&2
   exit 1
 fi
 
@@ -40,13 +44,12 @@ if [ "$TIMES_TO_RUN" == "" ]; then
   echo "Please provide how many times to rerun '--times 100' " >&2
   exit 1
 fi
-
 for ((i=1; i<="$TIMES_TO_RUN"; i++))
 do
-  JOB_ID=$(gh run view $VIEW_ID --json jobs --jq ".jobs[] | {name, databaseId} | select(.name == \"$JOB_NAME\") | .databaseId")
+  JOB_ID=$(gh run view "$VIEW_ID" --json jobs --jq ".jobs[] | {name, databaseId} | select(.name == \"$JOB_NAME\") | .databaseId")
 
   echo "🤞 Run \"$JOB_NAME\" on CI (Iteration $i, Job ID: $JOB_ID, View ID: $VIEW_ID)"
-  gh run rerun -j $JOB_ID
+  gh run rerun -j "$JOB_ID"
 
   # TODO: check for "job XXX cannot be rerun"
 
@@ -54,8 +57,8 @@ do
   while true; do
     sleep 10
 
-    JOB_STATUS=$(gh run view $VIEW_ID --job $JOB_ID --json status)
-    printf "\r⏳ Waiting job to complete: %s" $JOB_STATUS
+    JOB_STATUS=$(gh run view "$VIEW_ID" --job "$JOB_ID" --json status)
+    printf "\r⏳ Waiting job to complete: %s" "$JOB_STATUS"
 
     # Check if the job is done
     if [[ "$JOB_STATUS" == *"completed"* ]]; then
@@ -66,20 +69,20 @@ do
     ((counter++))
     # Waiting limit >=20 minutes (20m / 10s = 120s)
     if ((counter > 120)); then
-      echo "⌛️Waited too long for job to done, exiting"
+      echo "⌛️ Waited too long for job to done, exiting"
       exit 1
     fi
   done
 
   # gh run view $VIEW_ID --job $JOB_ID --json status
 
-  runConclusion=$(gh run view $VIEW_ID --job $JOB_ID --json conclusion)
+  runConclusion=$(gh run view "$VIEW_ID" --job "$JOB_ID" --json conclusion)
 
-  echo "\n$runConclusion"
+  printf "\n%s" "$runConclusion"
 
   # stop on failure
-  if [[ $(echo "$runConclusion" | jq -r '.conclusion') != "success" ]]; then
-      echo "❌Job failed, check CI logs for more details"
+  if [[ $(echo "$runConclusion" | jq -r ".conclusion") != "success" ]]; then
+      echo "❌ Job failed, check CI logs for more details"
       exit 1
   fi
 done
