Revert "add more logs"
This reverts commit 2f91a68b796ad61f730221f7e5350ff0224f5b42.

# Conflicts:
#	scripts/sns/aggregator/test-pagination

diff --git a/scripts/sns/aggregator/test-pagination b/scripts/sns/aggregator/test-pagination
--- a/scripts/sns/aggregator/test-pagination
+++ b/scripts/sns/aggregator/test-pagination
@@ -39,9 +39,6 @@ sns_from_wasm_canister() {
 }
 [[ "" != "${NUM_SNS:-}" ]] || NUM_SNS="$(sns_from_wasm_canister || sns_from_latest)"
 
-echo "sns_from_wasm_canister = $(sns_from_wasm_canister)"
-echo "sns_from_latest $(sns_from_latest)"
-
 (
   printf "\n\n\n=========================================\n"
   printf "%s\n" "Test that:" \
@@ -50,26 +47,20 @@ echo "sns_from_latest $(sns_from_latest)"
   PAGE_SIZE=10
   NUM_PAGES="$(((NUM_SNS / PAGE_SIZE) + 1))"
   for ((page = 0, sns_count = 0; ; page++)); do
-    echo "Testing page #${page}/${NUM_PAGES} PAGE_SIZE=${PAGE_SIZE} NUM_SNS=${NUM_SNS} sns_count=${sns_count}..."
+    echo "Testing page #${page}/${NUM_PAGES}..."
     # Get the page
     PAGE_FILE="$(mktemp aggregator-last-page-XXXXX.json)"
     curl -sSLf "${AGGREGATOR_CANISTER_URL}/v1/sns/list/page/${page}/slow.json" -o "$PAGE_FILE" || {
       echo "ERROR: Failed to get page #$page/${NUM_PAGES}"
       exit 1
     } >&2
-
-    printf "\n\n\n=========================================\n"
-    cat "$PAGE_FILE"
-    printf "\n\n\n=========================================\n"
-
     # Verify that the expected number of SNSs is present.
     expect=$((sns_count + PAGE_SIZE > NUM_SNS ? NUM_SNS - sns_count : PAGE_SIZE))
     actual="$(jq length "$PAGE_FILE")"
     sns_count=$((sns_count + actual))
-    ((expect == actual || expect == actual + 1)) || {
-      echo "ERROR1: Expected to have $expect SNS in the aggregator page $page but found $actual."
+    ((expect == actual)) || {
+      echo "ERROR: Expected to have $expect SNS in the aggregator page $page but found $actual."
       echo "Data is in: $PAGE_FILE"
-      # cat "$PAGE_FILE"
       exit 1
     } >&2
     page_size="$actual"
@@ -77,9 +68,8 @@ echo "sns_from_latest $(sns_from_latest)"
     expect="$(seq "$((PAGE_SIZE * page))" "$((sns_count - 1))")"
     actual="$(jq '.[]|.index' "$PAGE_FILE")"
     [[ "$expect" == "$actual" ]] || {
-      echo "ERROR2: Expected to have $expect SNS in the aggregator page $page but found $actual."
+      echo "ERROR: Expected to have $expect SNS in the aggregator page $page but found $actual."
       echo "Data is in: $PAGE_FILE"
-      # cat "$PAGE_FILE"
       exit 1
     } >&2
     # Clean up
