E2E: Screenshot test (#3051)
# Motivation

We want to detect regressions in layout/rendering/css with screenshot
comparisons.

# Changes

1. Add `frontend/src/tests/e2e/design.spec.ts` which takes screenshots
on the landing page and the wallet page.
2. Always update screenshots with running e2e tests on CI.
3. In the CI workflow, check if screenshots were updated and if so,
upload them in an artifact and make the workflow fail with instructions
to update the screenshots.
4. A script to download and update the screenshots
5. Some page object changes to support the new tests.

# Tests

I've manually changed the screenshots and the [test
failed](https://github.com/dfinity/nns-dapp/actions/runs/5808802464/job/15746389374)
with the following instructions:
```
Screenshots have changed:
frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Login-1-firefox-linux.png
frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-1-Google-Chrome-linux.png
frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-1-firefox-linux.png
frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-wide-screen-1-Google-Chrome-linux.png
frontend/src/tests/e2e/screenshots/design.spec.ts-Design-Signed-in-My-Tokens-wide-screen-1-firefox-linux.png

To update your local repo run:
  scripts/update-e2e-screenshots --run_id 5808802464
Error: Process completed with exit code 1.
```

After running the given command, the test passed.

# Todos

- [x] Add entry to changelog (if necessary).

---------

Co-authored-by: David Dal Busco <david.dalbusco@dfinity.org>
Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/.github/actions/test-e2e/action.yml b/.github/actions/test-e2e/action.yml
--- a/.github/actions/test-e2e/action.yml
+++ b/.github/actions/test-e2e/action.yml
@@ -50,7 +50,7 @@ runs:
       run: |
         export PLAYWRIGHT_BASE_URL="$(../scripts/dfx-canister-url nns-dapp)"
         PLAYWRIGHT_FILES="$(ls src/tests/e2e/${{ inputs.test_filter }} | cat | split -n r/${{ inputs.shard_number }}/${{ inputs.shard_count }})"
-        npm run test-e2e -- ${PLAYWRIGHT_FILES}
+        npm run test-e2e -- --update-snapshots ${PLAYWRIGHT_FILES:-}
     - name: Upload Playwright results
       uses: actions/upload-artifact@v3
       if: ${{ failure() }}
@@ -60,6 +60,34 @@ runs:
           frontend/playwright-report/*
           frontend/playwright-results/*
         retention-days: 3
+    - name: Check for screenshot changes
+      shell: bash
+      id: check-screenshots
+      run: |
+        if ! git diff --quiet -- frontend/src/tests/e2e/screenshots; then
+          echo "screenshots<<EOF" >> "$GITHUB_OUTPUT"
+          git diff --name-only -- frontend/src/tests/e2e/screenshots >> "$GITHUB_OUTPUT"
+          echo "EOF" >> "$GITHUB_OUTPUT"
+        fi
+    - name: Upload screenshots
+      if: ${{ steps.check-screenshots.outputs.screenshots }}
+      uses: actions/upload-artifact@v3
+      with:
+        name: updated-screenshots
+        path: |
+          ${{ steps.check-screenshots.outputs.screenshots }}
+        retention-days: 3
+    - name: Fail if screenshots changed
+      if: ${{ steps.check-screenshots.outputs.screenshots }}
+      shell: bash
+      # Fail in order to force updating the screenshots explicitly.
+      run: |
+        echo "Screenshots have changed:"
+        git diff --name-only -- frontend/src/tests/e2e/screenshots
+        echo
+        echo "To update your local repo run:"
+        echo "  scripts/update-e2e-screenshots --run_id ${{ github.run_id }}"
+        exit 1
     - name: Stop replica
       shell: bash
       run: dfx stop
