Handle empty

diff --git a/scripts/canister_ids b/scripts/canister_ids
--- a/scripts/canister_ids
+++ b/scripts/canister_ids
@@ -29,11 +29,11 @@ clap.define long=create desc="Create the json file if missing" variable=CREATE
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
 
-if ! [ -f "$JSON_FILE" ]; then
-  if [ "$CREATE" ]; then
+if ! [ -f "${JSON_FILE:-}" ]; then
+  if [ "${CREATE:-}" ]; then
     echo "{}" >"$JSON_FILE"
   else
-    echo "$JSON_FILE is missing." >&2
+    echo "${JSON_FILE:-} is missing." >&2
     exit 1
   fi
 fi
