Support icrc1 format in convert-id

diff --git a/scripts/convert-id b/scripts/convert-id
--- a/scripts/convert-id
+++ b/scripts/convert-id
@@ -36,7 +36,7 @@ source "$(clap.build)"
 
 function check_format() {
   case $1 in
-  text | hex | blob | account_identifier) ;;
+  text | hex | blob | account_identifier | icrc1) ;;
   *)
     echo "Invalid format: $1" >&2
     echo "Valid formats are: text, hex and blob" >&2
@@ -82,6 +82,15 @@ function blob_to_hex() {
 }
 
 function get_subaccount_hex() {
+  if [[ "$INPUT_FORMAT" = "icrc1" ]]; then
+    if [[ -n "${SUBACCOUNT_ARG}" ]]; then
+      echo "The ICRC1 format includes the subaccount so you can't specify a separate subaccount as well." >&2
+      exit 1
+    fi
+    subaccount_part=$(echo -n "$ID_ARG" | sed 's@^[^.]*\.@@')
+    printf '%064s' "$subaccount_part"
+    return
+  fi
   if [[ "$SUBACCOUNT_FORMAT" = "index" ]]; then
     SUBACCOUNT_ARG="${SUBACCOUNT_ARG:-0}"
     if ! [[ "$SUBACCOUNT_ARG" =~ ^[0-9]+$ ]]; then
@@ -116,6 +125,27 @@ function account_identifier_to_hex() {
   exit 1
 }
 
+function icrc1_to_hex() {
+  sed 's@-[^-]*$@@' | text_to_hex
+}
+
+function hex_to_icrc1() {
+  hex=$(cat)
+
+  subaccount_hex="$(get_subaccount_hex)"
+
+  subaccount_hex="$(echo -n "$subaccount_hex" | sed -e 's@^0*@@')"
+
+  if [[ -z "$subaccount_hex" ]]; then
+    echo -n "$hex" | hex_to_text
+    return
+  fi
+
+  checksum="$(echo -n "${hex}${subaccount_hex}" | xxd -r -p | /usr/bin/crc32 /dev/stdin | xxd -p -r | base32 | tr -d = | tr '[:upper:]' '[:lower:]')"
+
+  echo "$(echo "$hex" | hex_to_text)-${checksum}.${subaccount_hex}"
+}
+
 function check_hex() {
   if ! [[ $1 =~ ^([0-9a-fA-F]{2})+$ ]]; then
     echo "Invalid hex: $1" >&2
@@ -137,6 +167,13 @@ function check_text() {
   fi
 }
 
+function check_icrc1() {
+  if ! [[ $1 =~ ^[a-z0-9-]+\.[0-9a-f]+$ ]]; then
+    echo "Invalid icrc1: $1" >&2
+    exit 1
+  fi
+}
+
 function maybe_as_subaccount() {
   if [ "${AS_SUBACCOUNT:-}" != "true" ]; then
     cat
@@ -151,6 +188,7 @@ check_format "$INPUT_FORMAT"
 check_format "$OUTPUT_FORMAT"
 check_"$INPUT_FORMAT" "$1"
 
+ID_ARG="$1"
 SUBACCOUNT_ARG="${2:-}"
 
 echo -n "$1" | "${INPUT_FORMAT}_to_hex" | maybe_as_subaccount | "hex_to_${OUTPUT_FORMAT}"
