Support .tar.xz in dev-local-state.sh and dfx-snapshot-install

diff --git a/scripts/dfx-snapshot-install b/scripts/dfx-snapshot-install
--- a/scripts/dfx-snapshot-install
+++ b/scripts/dfx-snapshot-install
@@ -19,18 +19,31 @@ UNSET_BACKUP_DIR="$HOME/dfx-state-backup-generated-timestamp"
 # Source the clap.bash file ---------------------------------------------------
 source "$SOURCE_DIR/clap.bash"
 # Define options
-clap.define short=z long=snapshot-zip desc="The snapshot .zip file" variable=STATE_ZIP_FILE default="snapshot.zip"
+clap.define short=s long=snapshot desc="The snapshot .tar.xz or .zip file" variable=SNAPSHOT_ARCHIVE default="snapshot.tar.xz"
 clap.define short=b long=backup-dir desc="The backup directory to create" variable=BACKUP_DIR_ARG default="$UNSET_BACKUP_DIR"
 clap.define short=c long=clean desc="Extract a clean state from the .zip file, even if a cached directory with extracted state exists" variable=CLEAN nargs=0 default="false"
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
 
-if [ ! -f "$STATE_ZIP_FILE" ]; then
-  echo "State file $STATE_ZIP_FILE does not exist. Use --state-zip to specify a state .zip file as generated by dfx-state-save in the snsdemo repo."
+if [ ! -f "$SNAPSHOT_ARCHIVE" ]; then
+  echo "Snapshot file $SNAPSHOT_ARCHIVE does not exist. Use --snapshot to specify a snapshot .tar.xz or .zip file as generated by dfx-snapshot-save in the snsdemo repo."
   exit 1
 fi
 
-STATE_HASH="$(sha256sum "$STATE_ZIP_FILE" | cut -d' ' -f1)"
+extract() {
+  ARCHIVE="$1"
+  DESTINATION_DIR="$2"
+  if [ "${ARCHIVE%.zip}" != "$ARCHIVE" ]; then
+    unzip "$ARCHIVE" -d "$DESTINATION_DIR"
+  elif [ "${ARCHIVE%.tar.xz}" != "$ARCHIVE" ]; then
+    tar --extract --xz --file "$ARCHIVE" --directory "$DESTINATION_DIR"
+  else
+    echo "ERROR: Only .tar.xz and .zip snapshots are supported."
+    exit 1
+  fi
+}
+
+STATE_HASH="$(sha256sum "$SNAPSHOT_ARCHIVE" | cut -d' ' -f1)"
 
 STATE_DIR="$(dfx cache show)/snsdemo-state-$STATE_HASH"
 
@@ -43,7 +56,7 @@ else
   fi
   echo "Extracting state into $STATE_DIR"
   mkdir -p "$STATE_DIR"
-  unzip "$STATE_ZIP_FILE" -d "$STATE_DIR"
+  extract "$SNAPSHOT_ARCHIVE" "$STATE_DIR"
 fi
 
 TOP_DIR=$(git rev-parse --show-toplevel)
