++

diff --git a/scripts/dfx-nns-deploy-custom b/scripts/dfx-nns-deploy-custom
--- a/scripts/dfx-nns-deploy-custom
+++ b/scripts/dfx-nns-deploy-custom
@@ -27,16 +27,19 @@ rm -f nns-dapp.wasm nns-dapp_local.wasm
 : "Deploy nns-dapp with other NNS canisters"
 dfx nns install
 
-: "Verify that deployment matches local build"
-build_hash="$(sha256sum nns-dapp.wasm | awk '{print $1}')"
-deployed_hash="$(dfx canister info nns-dapp | awk '/Module hash/{print $3}')"
-if [[ "0x$build_hash" == "$deployed_hash" ]]; then
-  echo "Check passed: Installed wasm hash matches built wasm."
-else
-  {
-    echo "ERROR: Deployed nns-dapp hash does not match."
-    echo "Local build: ox$build_hash"
-    echo "Deployed:    $deployed_hash"
-    exit 1
-  } >&2
-fi
+: "Verify that deployment has the expected canisters"
+for canister_name in nns-dapp internet_identity; do
+  wasm="$(n="$canister_name" jq -r '.canisters[env.n].wasm' dfx.json)"
+  build_hash="$(sha256sum "$wasm" | awk '{print $1}')"
+  deployed_hash="$(dfx canister info "$canister_name" | awk '/Module hash/{print $3}')"
+  if [[ "0x$build_hash" == "$deployed_hash" ]]; then
+    echo "Check passed: Installed $canister_name matches local wasm."
+  else
+    {
+      echo "ERROR: Deployed $canister_name hash does not match."
+      echo "Local build: 0x$build_hash"
+      echo "Deployed:    $deployed_hash"
+      exit 1
+    } >&2
+  fi
+done
