Prevent installing a second snapshot before the previous one is restored (#4900)
# Motivation

When installing a snapshot, some files and directories are replaced with
ones from the snapshot and the originals are placed in a backup
directory.
If you try to install a snapshot again, things can get confusing easily.
Better to always restore the previous backup before installing the next.

# Changes

In `scripts/dfx-snapshot-install`, check if there is a directory with a
name following the standard state backup directory name pattern. If
there is, refuse to install the snapshot.

# Tests

Manually created a directory named `dfx-state-backup-123` and then tried
to run a snapshot. Got:
```
$ scripts/dfx-snapshot-start -s /Users/dskloet/snapshots/2024-05-16-ckUSDC.tar.xz
drwxr-xr-x  2 dskloet  staff  64 May 21 15:12 /Users/dskloet/dfx-state-backup-123
ERROR: Found existing backup directory. Restore the previous backup before installing a new snapshot.
sh: /Users/dskloet/dfx-state-backup-20240521_152046/restore.sh: No such file or directory
```

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary

diff --git a/scripts/dfx-snapshot-install b/scripts/dfx-snapshot-install
--- a/scripts/dfx-snapshot-install
+++ b/scripts/dfx-snapshot-install
@@ -25,6 +25,11 @@ clap.define short=c long=clean desc="Extract a clean state from the .zip file, e
 # Source the output file ----------------------------------------------------------
 source "$(clap.build)"
 
+if ls -ld "$HOME"/dfx-state-backup-* 2>/dev/null; then
+  echo "ERROR: Found existing backup directory. Restore the previous backup before installing a new snapshot."
+  exit 1
+fi
+
 if [ ! -f "$SNAPSHOT_ARCHIVE" ]; then
   echo "Snapshot file $SNAPSHOT_ARCHIVE does not exist. Use --snapshot to specify a snapshot .tar.xz or .zip file as generated by dfx-snapshot-save in the snsdemo repo."
   exit 1
