Make the build script more robust

diff --git a/scripts/docker-build b/scripts/docker-build
--- a/scripts/docker-build
+++ b/scripts/docker-build
@@ -1,6 +1,19 @@
 #!/usr/bin/env bash
 set -euo pipefail
-SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
+
+(("${BASH_VERSINFO[0]}" >= 5)) || {
+  echo "ERROR:  Please use a newer version of bash.  The minimum supported bash version is 5.  Yours appears to be '${BASH_VERSINFO[0]}'" >&2
+  exit 1
+}
+
+if test -d scripts && test -e Dockerfile; then
+  : "OK: We appear to be in the root of the repo."
+else
+  echo "ERROR: Please run from the root of the nns-dapp repo." >&2
+  exit 1
+fi
+
+SOURCE_DIR="$PWD/scripts"
 PATH="$SOURCE_DIR:$PATH"
 
 print_help() {
@@ -15,6 +28,10 @@ print_help() {
 	  - sns_aggregator.wasm
 	  - "nns-dapp-arg-${DFX_NETWORK}.did"
 	  - "nns-dapp-arg-${DFX_NETWORK}.bin"
+
+	Note: If the docker build fails, it may help to build from a clean cache:
+
+	  ./scripts/docker-build -- --no-cache
 
 	EOF
 }
