Automatically derive PR for github-mark-ready

diff --git a/scripts/github-mark-ready b/scripts/github-mark-ready
--- a/scripts/github-mark-ready
+++ b/scripts/github-mark-ready
@@ -22,19 +22,19 @@ source "$(clap.build)"
 URL="${1:-}"
 URL_PATTERN="https://github.com/([^/]*/[^/]*)/pull/([^/]*).*"
 
-if [[ -z "${URL:-}" ]]; then
-  print_help
-  exit 0
-fi
+if [[ -n "${URL:-}" ]]; then
+  if ! [[ "$URL" =~ $URL_PATTERN ]]; then
+    echo "Invalid URL: $URL" >&2
+    echo "URL should match the pattern: $URL_PATTERN" >&2
+    exit 1
+  fi
 
-if ! [[ "$URL" =~ $URL_PATTERN ]]; then
-  echo "Invalid URL: $URL" >&2
-  echo "URL should match the pattern: $URL_PATTERN" >&2
-  exit 1
+  REPO=$(echo "$URL" | sed -E "s|$URL_PATTERN|\\1|")
+  PR=$(echo "$URL" | sed -E "s|$URL_PATTERN|\\2|")
+else
+  PR=$(gh pr view --json number --jq '.number')
+  REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')
 fi
-
-REPO=$(echo "$URL" | sed -E "s|$URL_PATTERN|\\1|")
-PR=$(echo "$URL" | sed -E "s|$URL_PATTERN|\\2|")
 
 echo "Watching PR $PR on $REPO..."
 
