Debug exit 141

diff --git a/scripts/past-changelog-test b/scripts/past-changelog-test
--- a/scripts/past-changelog-test
+++ b/scripts/past-changelog-test
@@ -8,12 +8,22 @@ MAIN_ANCESTOR="$(git merge-base HEAD origin/main)"
 
 ignoreSigPipe() {
   error="$?"
+  echo "Ignoring SIGPIPE error $error"
   if [ "$error" = 141 ]; then
     return 0
   else
     return "$error"
   fi
 }
+
+echo test 3
+X="$((echo hoi && sleep 1 || ignoreSigPipe) | head -1)"
+echo test 4
+X="$((echo hoi && sleep 1) | head -1 || ignoreSigPipe)"
+echo test 2
+XX=$((ls && sleep 1; echo "? $?") | head -n 1)
+echo test 1
+(ls && sleep 1; echo "? $?") | head -n 1
 
 if ! LAST_ADDED_ENTRY_CONTENT="$(git diff "$MAIN_ANCESTOR" "$CHANGELOG" | grep '^+[*-]' | tail -1 | sed -e 's/^+//')"; then
   echo "PASSED: No new entries were added to $CHANGELOG"
