test incorrect change log entry

diff --git a/scripts/past-changelog-test b/scripts/past-changelog-test
--- a/scripts/past-changelog-test
+++ b/scripts/past-changelog-test
@@ -5,6 +5,16 @@ set -xeuo pipefail
 
 SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
 
-git diff "$(git merge-base HEAD origin/main)" "$SOURCE_DIR/../CHANGELOG-Nns-Dapp.md"
+CHANGELOG="CHANGELOG-Nns-Dapp.md"
+MAIN_ANCESTOR="$(git merge-base HEAD origin/main)"
 
-exit 1
+LAST_ADDED_ENTRY_CONTENT="$(git diff "$MAIN_ANCESTOR" "$CHANGELOG" | grep '^+[*-]' | tail -1 | sed -e 's/^+//')"
+LAST_ADDED_ENTRY_LINE_NUMBER="$(grep --fixed-string -n -m 1 -- "$LAST_ADDED_ENTRY_CONTENT" "$CHANGELOG")"
+LAST_RELEASE_LINE_NUMBER="$(grep -n -m 1 "^## Proposal \d\+$" "$CHANGELOG")"
+
+if [[ "$LAST_ADDED_ENTRY_LINE_NUMBER" > "$LAST_RELEASE_LINE_NUMBER" ]]; then
+  echo "ERROR: $CHANGELOG entries should not be added to existing releases." >&2
+  exit 1
+fi
+
+echo "PASSED"
