++

diff --git a/scripts/update-snsdemo b/scripts/update-snsdemo
--- a/scripts/update-snsdemo
+++ b/scripts/update-snsdemo
@@ -14,7 +14,13 @@ source "$(clap.build)"
 # Check that the snsdemo repository directory exists
 SNSDEMO_REPO="${SNSDEMO_REPO:-${1:-}}"
 test -e "${SNSDEMO_REPO:-}" || {
-  echo "ERROR: Please supply the path to the snsdemo repository with --snsdemo_repo" >&2
+  echo "ERROR: Please supply the path to the snsdemo repository with e.g. --dir ../some/path/" >&2
+  exit 1
+} >&2
+
+# Check that the release name has been specified
+test -n "${SNSDEMO_RELEASE:-}" || {
+  echo "ERROR: Please spcify the snsdemo release to upgrade to with e.g. --release release-YYYY-MM-DD"
   exit 1
 } >&2
 
