One build (#2744)
# Motivation
- Network errors are killing CI.
- The heaviest network usage is in building the canisters, either due to
downloading dependencies or from getting the docker cache.
- So let's build once and reuse.

# Changes
* Move the `docker-build` and `sns_aggregator` workflows into
`build.yaml`, where it can reuse the docker build.
* Add a workflow dispatch to `build.yaml`; this was available on
docker-build.

Note: I have studiously avoided making any "improvements" that are not
strictly required for this PR. Yes, to be sure, any reviewer is likely
to find bits that could be improved. But that is not the point of this
PR.

# TODO
- After this has been merged, remove the empty workflows as merge
requirements and make another PR deleting the workflows altogether.

# Tests
See how the docker build is now reused:

![Screenshot from 2023-06-22
17-43-22](https://github.com/dfinity/nns-dapp/assets/5982633/2176113f-d18b-46af-804b-68fb56ec75fd)

---------

Co-authored-by: Max Murphy-Skvorzov <max@winning.black>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: E2e test
+name: Build and test
 # We use "push" events so that we have the actual commit. In "pull_request"
 # events we get a merge commit with main instead. The merge commit can be
 # useful to check that the code would pass tests once merged, but here it just
@@ -6,6 +6,12 @@ name: E2e test
 # date before merge. It's also nice to have CI running on branches without PRs.
 on:
   push:
+  workflow_dispatch:
+    inputs:
+      no_cache:
+        description: 'no-cache'
+        default: false
+        type: boolean
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
@@ -40,6 +46,12 @@ jobs:
         with:
           name: sns_aggregator_dev
           path: out/sns_aggregator_dev.wasm.gz
+          retention-days: 3
+      - name: 'Upload whole out directory'
+        uses: actions/upload-artifact@v3
+        with:
+          name: out
+          path: out
           retention-days: 3
   test-playwright-e2e:
     needs: build
@@ -326,8 +338,200 @@ jobs:
           diff local_hashes.txt mainnet_hashes.txt  || {
             echo "ERROR: wasm hashes differ between mainnet and local."
           }
+  aggregator_test:
+    needs: build
+    runs-on: ubuntu-20.04
+    timeout-minutes: 60
+    steps:
+      - name: Checkout nns-dapp
+        uses: actions/checkout@v3
+      - name: Get docker build outputs
+        uses: actions/download-artifact@v3
+        with:
+          name: out
+          path: out
+      - name: Get SNS scripts
+        uses: actions/checkout@v3
+        with:
+          repository: 'dfinity/snsdemo'
+          path: 'snsdemo'
+          # Version from 2023-06-06 with dfx v0.14.1
+          ref: '0e61f618018db099a01b1686535fff8eff980d1c'
+      - name: Add SNS scripts to the path
+        run: |
+          echo "$PWD/snsdemo/bin" >> $GITHUB_PATH
+      - name: Install tools
+        run: |
+          dfx-software-dfx-install --version "$(jq -r .dfx dfx.json)"
+          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/181b5293e73cfe16f7a79c5b3a4339bd522d31f3/install-from-binstall-release.sh | bash
+          cargo binstall --no-confirm "idl2json_cli@$(jq -r .defaults.build.config.IDL2JSON_VERSION dfx.json)"
+      - name: Get test environment
+        run: |
+          curl -fL --retry 5 https://github.com/dfinity/snsdemo/releases/download/release-2023-06-06/snsdemo_snapshot_ubuntu-22.04.tar.xz > state.tar.xz
+          dfx-snapshot-restore --snapshot state.tar.xz --verbose
+          dfx identity use snsdemo8
+          dfx-sns-demo-healthcheck
+      - name: Upgrade to the current aggregator
+        run: |
+          cp out/sns_aggregator_dev.wasm.gz sns_aggregator.wasm.gz
+          # Note: Pretty much any argument values will do; the canister will be reconfigured.
+          dfx canister install sns_aggregator --wasm sns_aggregator.wasm.gz --mode reinstall --yes --upgrade-unchanged '(opt record { update_interval_ms = 1000; fast_interval_ms = 1_000_000_000; })'
+          dfx canister call sns_aggregator get_canister_config
+      - name: Verify that configuration is as provided
+        run: scripts/sns/aggregator/test-config
+      - name: Make the aggregator collect data quickly
+        run: dfx canister call sns_aggregator reconfigure '(opt record { update_interval_ms = 100; fast_interval_ms = 1_000_000_000; })'
+      - name: Wait for the aggregator to get data
+        run: sleep 120
+        # sleep time > 12 SnS & 2 block heights each + a few extra calls.
+        # TODO: The aggregator can be installed and populated in the saved state, so this sleep is not needed.
+      - name: Get the latest data from the sns aggregator
+        run: |
+          AGGREGATOR_CANISTER_ID="$(dfx canister id sns_aggregator)"
+          curl -Lf "http://${AGGREGATOR_CANISTER_ID}.localhost:8080/v1/sns/list/latest/slow.json" | tee aggregate-1.json
+          expect=10
+          actual="$(jq length aggregate-1.json)"
+          (( expect == actual ))  || {
+            echo ERROR: Expected to have $expect SNS in the aggregator but found $actual.
+            scripts/sns/aggregator/get_log
+          }
+      - name: Get the first page of data from the sns aggregator
+        run: |
+          AGGREGATOR_CANISTER_ID="$(dfx canister id sns_aggregator)"
+          curl --retry 5 -Lf "http://${AGGREGATOR_CANISTER_ID}.localhost:8080/v1/sns/list/page/0/slow.json" | tee aggregate-1.json || {
+            echo "ERROR: Failed to get data."
+            scripts/sns/aggregator/get_log
+          }
+          expect=10
+          actual="$(jq length aggregate-1.json)"
+          (( expect == actual ))  || {
+            echo ERROR: Expected to have $expect SNS in the aggregator but found $actual.
+            scripts/sns/aggregator/get_log
+          }
+      - name: Get the second page of data from the sns aggregator
+        run: |
+          AGGREGATOR_CANISTER_ID="$(dfx canister id sns_aggregator)"
+          curl -Lf "http://${AGGREGATOR_CANISTER_ID}.localhost:8080/v1/sns/list/page/1/slow.json" | tee aggregate-1.json
+          expect=2
+          actual="$(jq length aggregate-1.json)"
+          (( expect == actual ))  || {
+            echo ERROR: Expected to have $expect SNS in the aggregator but found $actual.
+          }
+      - name: Get logs
+        run: |
+          scripts/sns/aggregator/get_log > ,logs
+          LOG_LINES="$(wc -l <,logs)"
+          (( LOG_LINES > 10 )) || {
+            echo "ERROR: Expected a non-trivial number of lines to have been logged by now but found only ${LOG_LINES}"
+            cat ,logs
+            exit 1
+          }
+      - name: Upgrade the aggregator to self with a slow refresh rate
+        run: dfx canister install --mode upgrade --wasm sns_aggregator.wasm.gz --upgrade-unchanged sns_aggregator '(opt record { update_interval_ms = 1_000_000_000; fast_interval_ms = 1_000_000_000; })'
+      - name: Expect the first page of data to be retained over the upgrade
+        run: |
+          AGGREGATOR_CANISTER_ID="$(dfx canister id sns_aggregator)"
+          curl -Lf "http://${AGGREGATOR_CANISTER_ID}.localhost:8080/v1/sns/list/page/0/slow.json" | tee aggregate-1.json
+          expect=10
+          actual="$(jq length aggregate-1.json)"
+          (( expect == actual ))  || {
+            echo ERROR: Expected to have $expect SNS in the aggregator but found $actual.
+          }
+      - name: Expect the latest data to be retained over the upgrade
+        run: |
+          AGGREGATOR_CANISTER_ID="$(dfx canister id sns_aggregator)"
+          curl -Lf "http://${AGGREGATOR_CANISTER_ID}.localhost:8080/v1/sns/list/latest/slow.json" | tee aggregate-1.json
+          expect=10
+          actual="$(jq length aggregate-1.json)"
+          (( expect == actual ))  || {
+            echo ERROR: Expected to have $expect SNS in the aggregator but found $actual.
+          }
+      - name: Expect the upstream data to be retained over the upgrade
+        run: |
+          ./scripts/sns/aggregator/get_stable_data
+          expect=12
+          actual="$(jq '.sns_cache.upstream_data | length' stable_data.json)"
+          (( expect == actual ))  || {
+            echo ERROR: Expected to have $expect SNS in the aggregator upstream data but found $actual.
+          }
+      - name: Downgrade to prod and upgrade back again
+        run: |
+          set -euxo pipefail
+          git fetch --depth 1 origin tag aggregator-prod
+          diff="$(git diff tags/aggregator-prod rs/sns_aggregator)"
+          if test -n "${diff:-}"
+          then ./scripts/sns/aggregator/downgrade-upgrade-test -w sns_aggregator.wasm.gz --verbose
+          else echo "Skipping test as there are no relevant code changes"
+          fi
+      - name: Stop replica
+        run: dfx stop
+  assets:
+    name: "Upload assets"
+    needs: build
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+      - name: Get docker build outputs
+        uses: actions/download-artifact@v3
+        with:
+          name: out
+          path: out
+      - name: Print the hash of all assets
+        run: find out -type f | xargs sha256sum
+      - name: 'Record the git commit and any tags'
+        run: git log | head -n1 > out/commit.txt
+      - name: 'Upload ${{ matrix.BUILD_NAME }} nns-dapp wasm module'
+        uses: actions/upload-artifact@v3
+        with:
+          name: nns-dapp for ${{ matrix.BUILD_NAME }}
+          path: |
+            out/commit.txt
+            out/nns-dapp.wasm.gz
+            out/nns-dapp-arg-${{ matrix.DFX_NETWORK }}.did
+            out/nns-dapp-arg-${{ matrix.DFX_NETWORK }}.bin
+            out/frontend-config.sh
+            out/deployment-config.json
+      - name: 'Upload sns_aggregator wasm module'
+        uses: actions/upload-artifact@v3
+        with:
+          name: sns_aggregator for ${{ matrix.BUILD_NAME }}
+          path: |
+            out/sns_aggregator.wasm.gz
+            out/sns_aggregator_dev.wasm.gz
+      - name: Release
+        uses: ./.github/actions/release_nns_dapp
+        with:
+          assets_dir: 'out'
+          token: ${{ secrets.GITHUB_TOKEN }}
+      - name: 'Upload frontend assets'
+        uses: actions/upload-artifact@v3
+        with:
+          name: NNS frontend assets
+          path: |
+            out/assets.tar.xz
+            out/sourcemaps.tar.xz
+      - name: "Link the build sha to this commit"
+        run: |
+          : Set up git
+          git config user.name "GitHub Actions Bot"
+          git config user.email "<>"
+          : Make a note of the WASM shasum.
+          NOTE="refs/notes/mainnet/wasm-sha"
+          SHA="$(sha256sum < "out/nns-dapp.wasm.gz")"
+          git fetch origin "+${NOTE}:${NOTE}"
+          if git notes --ref="wasm-sha" add -m "$SHA"
+          then git push origin "${NOTE}:${NOTE}" || true
+          else echo SHA already set
+          fi
+      - name: "Verify that the WASM module is small enough to deploy"
+        run: |
+          wasm_size="$(wc -c < "out/nns-dapp.wasm.gz")"
+          max_size=3145728
+          echo "WASM size:          $wasm_size"
+          echo "Max supported size: $max_size"
+          (( wasm_size <= max_size )) || { echo "The WASM is too large" ; exit 1 ; }
   build-pass:
-    needs: ["build", "test-playwright-e2e", "test-rest", "network_independent_wasm"]
+    needs: ["build", "test-playwright-e2e", "test-rest", "network_independent_wasm", "aggregator_test", "assets"]
     if: ${{ always() }}
     runs-on: ubuntu-20.04
     steps:
