Shuffle steps around to make sure the dapp is ready

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,17 +65,6 @@ jobs:
           jq '.canisters.internet_identity.remote.id={}' dfx.json > dfx.json.v2 && mv dfx.json.v2 dfx.json
           curl --retry 5 --fail -sSL "https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity_dev.wasm" -o internet_identity_dev.wasm
           dfx canister install internet_identity --wasm internet_identity_dev.wasm --upgrade-unchanged --mode reinstall --yes
-      - name: Verify that arguments are set in index.html
-        run: |
-          go install github.com/ericchiang/pup@latest
-          curl "http://$(dfx canister id nns-dapp).localhost:8080/" | gunzip | pup 'head meta[name="nns-dapp-vars"] json{}' | tee nns_dapp_args_in_page.json
-          echo "Check a few values:"
-          for key in data-own-canister-id data-fetch-root-key data-identity-service-url ; do
-            # Verify that the key is non-trivial:
-            # jq -e returns an error code if the value is missing
-            # grep ... fails if the value is implausibly short.
-            key="$key" jq -re '.[0][env.key]' nns_dapp_args_in_page.json | grep -E ...
-          done
       - name: Basic downgrade-upgrade test
         run: |
           git fetch --depth 1 origin tag prod
@@ -83,6 +72,26 @@ jobs:
           then ./scripts/nns-dapp/downgrade-upgrade-test -w nns-dapp.wasm
           else echo "Skipping test as there are no relevant code changes"
           fi
+      - name: Wait for aggregator to get all SNSs
+        run: |
+          set +x
+          for (( try=300; try>0; try-- )); do
+             num_sns="$(for ((page=0; page<3; page++)) ; do { curl -fsS "http://$(dfx canister id sns_aggregator).localhost:8080/v1/sns/list/page/$page/slow.json" | jq length ; } 2>/dev/null || true ; done | awk '{i+=$1}END{print i}')"
+             (( num_sns < 12)) || break
+             printf "\r #SNS: % 4d   Tries remaining: %4d" "$num_sns" "$try"
+             sleep 2
+          done
+      - name: Verify that arguments are set in index.html
+        run: |
+          go install github.com/ericchiang/pup@latest
+          curl -sS --retry 10 "http://$(dfx canister id nns-dapp).localhost:8080/" | gunzip | pup 'head meta[name="nns-dapp-vars"] json{}' | tee nns_dapp_args_in_page.json
+          echo "Check a few values:"
+          for key in data-own-canister-id data-fetch-root-key data-identity-service-url ; do
+            # Verify that the key is non-trivial:
+            # jq -e returns an error code if the value is missing
+            # grep ... fails if the value is implausibly short.
+            key="$key" jq -re '.[0][env.key]' nns_dapp_args_in_page.json | grep -E ...
+          done
       - name: Rename nns-dapp.wasm for upload
         run: cp nns-dapp.wasm nns-dapp_local.wasm
       - name: 'Upload nns-dapp_local wasm module'
@@ -111,15 +120,6 @@ jobs:
         working-directory: frontend
         run: |
           npm ci
-      - name: Wait for aggregator to get all SNSs
-        run: |
-          set +x
-          for (( try=300; try>0; try-- )); do
-             num_sns="$(for ((page=0; page<3; page++)) ; do { curl -fsS "http://$(dfx canister id sns_aggregator).localhost:8080/v1/sns/list/page/$page/slow.json" | jq length ; } 2>/dev/null || true ; done | awk '{i+=$1}END{print i}')"
-             (( num_sns < 12)) || break
-             printf "\r #SNS: % 4d   Tries remaining: %4d" "$num_sns" "$try"
-             sleep 2
-          done
       - name: Run Playwright end-to-end tests
         working-directory: frontend
         run: npm run test-e2e
