Set -eu by default

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,8 +13,9 @@ on:
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
-env:
-  NNS_CACHING_KEY: dv-0004
+defaults:
+  run:
+    shell: bash -euxlo pipefail {0}
 jobs:
   build:
     runs-on: ubuntu-20.04
@@ -124,9 +125,9 @@ jobs:
           SCREENSHOT=1 npm run test |& tee -a chrome-wdio.log
       - name: Run firefox e2e tests
         working-directory: e2e-tests
+        # Allow Firefox to fail until the source of flakiness is found and fixed.
+        continue-on-error: true
         run: |
-          # Allow Firefox to fail until the source of flakiness is found and fixed.
-          # set -o pipefail
           export WDIO_BROWSER=firefox
           SCREENSHOT=1 npm run test |& tee -a firefox-wdio.log
       - name: Get the postinstall instruction count
