Fix CI required checks (#1759)
# Motivation
A PR was merged even though the corresponding test failed. If a
dependent test failed, the final check is skipped and historically that
would prevent the PR from merging. It seems that "needs" is now treated
as a conditional, so "skipped" is treated as success.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
This is not desired

# Changes
- Always run the final check, to see whether required GitHub jobs have
succeeded.

# Tests
- I made a toy job that always fails, set it as a dependency and
verified that the final check was run, not skipped, and failed.
- I repeated the same with the toy job succeeding, and the final check
similarly succeeded.

Co-authored-by: Max Murphy-Skvorzov <max@winning.black>

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -139,7 +139,13 @@ jobs:
           SHELLCHECK_OPTS: -e SC1090 -e SC2119 -e SC1091
   checks-pass:
     needs: ["formatting", "cargo-tests", "svelte-lint", "svelte-tests", "shell-checks", "e2e-lint"]
+    if: ${{ always() }}
     runs-on: ubuntu-20.04
     steps:
       - name: Checks workflow passes
-        run: echo OK
+        run: |
+          if echo '${{ toJson(needs) }}' | jq 'to_entries[] | select(.value.result != "success")' | grep .
+          then echo "You shall not pass:  Some required tests did not succeed"
+               exit 1
+          else echo "Congratulations, young Frodo."
+          fi
