Always run the final test

diff --git a/.github/workflows/tag.yaml b/.github/workflows/tag.yaml
--- a/.github/workflows/tag.yaml
+++ b/.github/workflows/tag.yaml
@@ -21,7 +21,13 @@ jobs:
           git push origin tags/tip -f
   tag_pass:
     needs: ["tag_tip"]
+    if: ${{ always() }}
     runs-on: ubuntu-20.04
     steps:
-      - name: Tag workflow passes
-        run: echo OK
+      - name: Checks workflow passes
+        run: |
+          if echo '${{ toJson(needs) }}' | jq 'to_entries[] | select(.value.result != "success")' | grep .
+          then echo "You shall not pass:  Some required tests did not succeed"
+               exit 1
+          else echo "Congratulations, young Frodo."
+          fi
